### ISSUE TITLE
Complex/imaginary numbers?

### ISSUE THREAD

**Issue by kleiram** [JordanRL/Fermat#14]
I thought that maybe it'd be nice if complex numbers are supported including their operations.

I've created this issue mainly because I wanted to check if it's actually something @JordanRL wants in this project. If so, I think I can get started on a PR.

**Comment by JordanRL** [comment]
Sorry for the delay in replying, I've been very busy the last few months with day-to-day work.

Supporting complex numbers is definitely something I was hoping to add at some point, and unlike things like currency/finance operations, or geometry operations, I think it makes sense to add it into the base Fermat library.

I would definitely welcome work on supporting complex numbers. Make sure to look at the [contribution guidelines](https://github.com/JordanRL/Fermat/blob/master/CONTRIBUTING.md), but so long as there are tests for the code and it conforms generally to the style used in the rest of the library, any productive work would be greatly appreciated.

I'm currently thinking about ways to increase the precision limits without storing even larger constants, as well as scoping the Fermat-Currency and Fermat-Geometry modules.

**Comment by kleiram** [comment]
No worries about the delay! I know the feeling (as can be seen by my respons time right now).

I'm definitely motivated to start working on this, but I might need a little push in the right direction on how to best structure everything, right now I was thinking of maybe defining a new interface, although maybe even that is not necessary.

I'll create a WIP pull request and start working on that, ok?

**Comment by JordanRL** [comment]
Sounds good to me.

A new interface implies new methods. Are you thinking of making new methods that explicitly allow imaginary responses for things like sqrt(), trig functions, etc?

**Comment by JordanRL** [comment]
Hey @kleiram is this still something that you want to help with? I'll be starting on my own implementation of this in the next few weeks, and even if you're not up for writing code I'd certainly welcome your input on how to handle complex numbers in this library.
